allowBuilds:
  esbuild: false

minimumReleaseAgeExclude:
  - "@block65/oxlint-plugin@0.6.0"
  - "@block65/shared-config@0.3.0"

overrides:
  oxlint: npm:@block65/oxlint@>=1.82.0
  oxlint-tsgolint: npm:@block65/oxlint-tsgolint@>=7.0.2001
