/**
 * This file is auto generated by @block65/openapi-codegen
 *
 * WARN: Do not edit directly.
 *
 * Generated on 2023-05-11T04:29:01.276Z
 *
 */
import {
  RestServiceClient,
  createIsomorphicNativeFetcher,
  type RestServiceClientConfig,
} from '../../../src/main.js';
import {
  type GetOperationCommandInput,
  type ListBillingAccountsCommandInput,
  type CreateBillingAccountCommandInput,
  type GetBillingAccountCommandInput,
  type UpdateBillingAccountCommandInput,
  type GetBillingAccountPortalCommandInput,
  type LinkBillingAccountCommandInput,
  type ListPaymentMethodsCommandInput,
  type CreatePaymentMethodCommandInput,
  type GetPaymentMethodFromStripeCommandInput,
  type GetPaymentMethodCommandInput,
  type UpdatePaymentMethodCommandInput,
  type DeletePaymentMethodCommandInput,
  type ListBillingSubscriptionsCommandInput,
  type CreateBillingSubscriptionCommandInput,
  type UpdateBillingSubscriptionCommandInput,
  type CancelSubscriptionCommandInput,
  type UpdateBillingSubscriptionPromoCodeCommandInput,
  type LongRunningOperation,
  type BillingAccountList,
  type BillingAccount,
  type BillingAccountPortal,
  type PaymentMethods,
  type PaymentMethodIntendedLro,
  type PaymentMethod,
  type PaymentMethodDeletedLro,
  type BillingSubscriptions,
  type BillingSubscriptionLro,
} from './types.js';

type AllInputs =
  | GetOperationCommandInput
  | ListBillingAccountsCommandInput
  | CreateBillingAccountCommandInput
  | GetBillingAccountCommandInput
  | UpdateBillingAccountCommandInput
  | GetBillingAccountPortalCommandInput
  | LinkBillingAccountCommandInput
  | ListPaymentMethodsCommandInput
  | CreatePaymentMethodCommandInput
  | GetPaymentMethodFromStripeCommandInput
  | GetPaymentMethodCommandInput
  | UpdatePaymentMethodCommandInput
  | DeletePaymentMethodCommandInput
  | ListBillingSubscriptionsCommandInput
  | CreateBillingSubscriptionCommandInput
  | UpdateBillingSubscriptionCommandInput
  | CancelSubscriptionCommandInput
  | UpdateBillingSubscriptionPromoCodeCommandInput;
type AllOutputs =
  | LongRunningOperation
  | BillingAccountList
  | BillingAccount
  | BillingAccountPortal
  | PaymentMethods
  | PaymentMethodIntendedLro
  | PaymentMethod
  | PaymentMethodDeletedLro
  | BillingSubscriptions
  | BillingSubscriptionLro;

export class BillingServiceRestApiRestClient extends RestServiceClient<
  AllInputs,
  AllOutputs
> {
  constructor(
    baseUrl = new URL('https://api.example.com/'),
    fetcher = createIsomorphicNativeFetcher(),
    config?: RestServiceClientConfig,
  ) {
    super(baseUrl, fetcher, config);
  }
}
