/**
 * @generated by @block65/openapi-codegen
 *
 * Do not edit directly
 */

import * as commands from "./commands.js";
import * as schemas from "./valibot.js";

export class ImportBillingDataCommand
	extends commands.ImportBillingDataCommand
{
	public override readonly responseSchema =
		schemas.importBillingDataCommandResponseSchema;
}

export class GetOperationCommand extends commands.GetOperationCommand {
	public override readonly responseSchema =
		schemas.getOperationCommandResponseSchema;
}

export class StreamOperationEventsCommand
	extends commands.StreamOperationEventsCommand
{
	public override readonly dataSchema =
		schemas.streamOperationEventsCommandDataSchema;
}

export class ListBillingAccountsCommand
	extends commands.ListBillingAccountsCommand
{
	public override readonly responseSchema =
		schemas.listBillingAccountsCommandResponseSchema;
}

export class CreateBillingAccountCommand
	extends commands.CreateBillingAccountCommand
{
	public override readonly responseSchema =
		schemas.createBillingAccountCommandResponseSchema;
}

export class GetBillingAccountCommand
	extends commands.GetBillingAccountCommand
{
	public override readonly responseSchema =
		schemas.getBillingAccountCommandResponseSchema;
}

export class UpdateBillingAccountCommand
	extends commands.UpdateBillingAccountCommand
{
	public override readonly responseSchema =
		schemas.updateBillingAccountCommandResponseSchema;
}

export class GetBillingAccountPortalCommand
	extends commands.GetBillingAccountPortalCommand
{
	public override readonly responseSchema =
		schemas.getBillingAccountPortalCommandResponseSchema;
}

export class ListPaymentMethodsCommand
	extends commands.ListPaymentMethodsCommand
{
	public override readonly responseSchema =
		schemas.listPaymentMethodsCommandResponseSchema;
}

export class CreatePaymentMethodCommand
	extends commands.CreatePaymentMethodCommand
{
	public override readonly responseSchema =
		schemas.createPaymentMethodCommandResponseSchema;
}

export class GetPaymentMethodFromStripeCommand
	extends commands.GetPaymentMethodFromStripeCommand
{
	public override readonly responseSchema =
		schemas.getPaymentMethodFromStripeCommandResponseSchema;
}

export class GetPaymentMethodCommand extends commands.GetPaymentMethodCommand {
	public override readonly responseSchema =
		schemas.getPaymentMethodCommandResponseSchema;
}

export class DeletePaymentMethodCommand
	extends commands.DeletePaymentMethodCommand
{
	public override readonly responseSchema =
		schemas.deletePaymentMethodCommandResponseSchema;
}

export class ListBillingSubscriptionsCommand
	extends commands.ListBillingSubscriptionsCommand
{
	public override readonly responseSchema =
		schemas.listBillingSubscriptionsCommandResponseSchema;
}

export class CreateBillingSubscriptionCommand
	extends commands.CreateBillingSubscriptionCommand
{
	public override readonly responseSchema =
		schemas.createBillingSubscriptionCommandResponseSchema;
}

export class UpdateBillingSubscriptionPromoCodeCommand
	extends commands.UpdateBillingSubscriptionPromoCodeCommand
{
	public override readonly responseSchema =
		schemas.updateBillingSubscriptionPromoCodeCommandResponseSchema;
}

export {
	CancelSubscriptionCommand,
	LinkBillingAccountCommand,
	UpdateBillingSubscriptionCommand,
	UpdatePaymentMethodCommand,
} from "./commands.js";
