/**
 * @generated by @block65/openapi-codegen
 *
 * Do not edit directly
 */

import {
	Command,
	EventStreamCommand,
	jsonStringify,
} from "@block65/rest-client";
import type { UndefinedOnPartialDeep } from "type-fest";
import type {
	ImportBillingDataCommandHeader,
	ImportBillingDataCommandBodyNonJson,
	ImportBillingDataCommandParams,
	LongRunningOperation,
	GetOperationCommandInput,
	StreamOperationEventsCommandInput,
	StreamOperationEventsCommandOutput,
	ListBillingAccountsCommandInput,
	BillingAccountList,
	CreateBillingAccountCommandInput,
	BillingAccount,
	GetBillingAccountCommandInput,
	UpdateBillingAccountCommandInput,
	GetBillingAccountPortalCommandInput,
	BillingAccountPortal,
	LinkBillingAccountCommandInput,
	ListPaymentMethodsCommandInput,
	PaymentMethods,
	CreatePaymentMethodCommandInput,
	PaymentMethodIntendedLro,
	GetPaymentMethodFromStripeCommandInput,
	PaymentMethod,
	GetPaymentMethodCommandInput,
	UpdatePaymentMethodCommandInput,
	DeletePaymentMethodCommandInput,
	PaymentMethodDeletedLro,
	ListBillingSubscriptionsCommandInput,
	BillingSubscriptions,
	CreateBillingSubscriptionCommandInput,
	BillingSubscriptionLro,
	UpdateBillingSubscriptionCommandInput,
	CancelSubscriptionCommandInput,
	UpdateBillingSubscriptionPromoCodeCommandInput,
} from "./types.js";

/**
 * Tagged template literal that applies encodeURIComponent to all interpolated
 * values, protecting path integrity from characters like `/` and `#`.
 * @example encodePath`/users/${userId}` // "/users/foo%2Fbar"
 */
function encodePath(strings: TemplateStringsArray, ...values: string[]) {
	return String.raw(
		{ raw: strings },
		...values.map((value) => encodeURIComponent(value)),
	);
}

/**
 * ImportBillingDataCommand
 *
 */
export class ImportBillingDataCommand extends Command<
	ImportBillingDataCommandBodyNonJson &
		UndefinedOnPartialDeep<ImportBillingDataCommandParams>,
	LongRunningOperation,
	never,
	ImportBillingDataCommandHeader
> {
	public override method = "post" as const;

	constructor(
		input: ImportBillingDataCommandBodyNonJson &
			UndefinedOnPartialDeep<ImportBillingDataCommandParams>,
		headers: ImportBillingDataCommandHeader,
	) {
		const { billingAccountId, body } = input;
		super(
			encodePath`/billing-accounts/${billingAccountId}/import`,
			body,
			undefined,
			headers,
		);
	}
}

/**
 * GetOperationCommand
 *
 */
export class GetOperationCommand extends Command<
	UndefinedOnPartialDeep<GetOperationCommandInput>,
	LongRunningOperation
> {
	public override method = "get" as const;

	constructor(input: UndefinedOnPartialDeep<GetOperationCommandInput>) {
		const { operationId } = input;
		super(encodePath`/operations/${operationId}`);
	}
}

/**
 * StreamOperationEventsCommand
 *
 */
export class StreamOperationEventsCommand extends EventStreamCommand<
	UndefinedOnPartialDeep<StreamOperationEventsCommandInput>,
	StreamOperationEventsCommandOutput
> {
	public override method = "get" as const;

	constructor(
		input: UndefinedOnPartialDeep<StreamOperationEventsCommandInput>,
	) {
		const { operationId } = input;
		super(encodePath`/operations/${operationId}/events`);
	}
}

/**
 * ListBillingAccountsCommand
 *
 */
export class ListBillingAccountsCommand extends Command<
	UndefinedOnPartialDeep<ListBillingAccountsCommandInput>,
	BillingAccountList
> {
	public override method = "get" as const;

	constructor() {
		super("/billing-accounts");
	}
}

/**
 * CreateBillingAccountCommand
 *
 */
export class CreateBillingAccountCommand extends Command<
	UndefinedOnPartialDeep<CreateBillingAccountCommandInput>,
	BillingAccount
> {
	public override method = "post" as const;

	constructor(input: UndefinedOnPartialDeep<CreateBillingAccountCommandInput>) {
		const body = input;
		super("/billing-accounts", jsonStringify(body));
	}
}

/**
 * GetBillingAccountCommand
 *
 */
export class GetBillingAccountCommand extends Command<
	UndefinedOnPartialDeep<GetBillingAccountCommandInput>,
	BillingAccount
> {
	public override method = "get" as const;

	constructor(input: UndefinedOnPartialDeep<GetBillingAccountCommandInput>) {
		const { billingAccountId } = input;
		super(encodePath`/billing-accounts/${billingAccountId}`);
	}
}

/**
 * UpdateBillingAccountCommand
 *
 */
export class UpdateBillingAccountCommand extends Command<
	UndefinedOnPartialDeep<UpdateBillingAccountCommandInput>,
	BillingAccount
> {
	public override method = "put" as const;

	constructor(input: UndefinedOnPartialDeep<UpdateBillingAccountCommandInput>) {
		const { billingAccountId, ...body } = input;
		super(
			encodePath`/billing-accounts/${billingAccountId}`,
			jsonStringify(body),
		);
	}
}

/**
 * GetBillingAccountPortalCommand
 *
 */
export class GetBillingAccountPortalCommand extends Command<
	UndefinedOnPartialDeep<GetBillingAccountPortalCommandInput>,
	BillingAccountPortal
> {
	public override method = "post" as const;

	constructor(
		input: UndefinedOnPartialDeep<GetBillingAccountPortalCommandInput>,
	) {
		const { billingAccountId, ...body } = input;
		super(
			encodePath`/billing-accounts/${billingAccountId}/portal`,
			jsonStringify(body),
		);
	}
}

/**
 * LinkBillingAccountCommand
 *
 */
export class LinkBillingAccountCommand extends Command<
	UndefinedOnPartialDeep<LinkBillingAccountCommandInput>,
	never
> {
	public override method = "post" as const;

	constructor(input: UndefinedOnPartialDeep<LinkBillingAccountCommandInput>) {
		const { billingAccountId, ...body } = input;
		super(
			encodePath`/billing-accounts/${billingAccountId}/link`,
			jsonStringify(body),
		);
	}
}

/**
 * ListPaymentMethodsCommand
 *
 */
export class ListPaymentMethodsCommand extends Command<
	UndefinedOnPartialDeep<ListPaymentMethodsCommandInput>,
	PaymentMethods
> {
	public override method = "get" as const;

	constructor(input: UndefinedOnPartialDeep<ListPaymentMethodsCommandInput>) {
		const { billingAccountId } = input;
		super(encodePath`/billing-accounts/${billingAccountId}/payment-methods`);
	}
}

/**
 * CreatePaymentMethodCommand
 *
 */
export class CreatePaymentMethodCommand extends Command<
	UndefinedOnPartialDeep<CreatePaymentMethodCommandInput>,
	PaymentMethodIntendedLro
> {
	public override method = "post" as const;

	constructor(input: UndefinedOnPartialDeep<CreatePaymentMethodCommandInput>) {
		const { billingAccountId } = input;
		super(encodePath`/billing-accounts/${billingAccountId}/payment-methods`);
	}
}

/**
 * GetPaymentMethodFromStripeCommand
 *
 */
export class GetPaymentMethodFromStripeCommand extends Command<
	UndefinedOnPartialDeep<GetPaymentMethodFromStripeCommandInput>,
	PaymentMethod
> {
	public override method = "get" as const;

	constructor(
		input: UndefinedOnPartialDeep<GetPaymentMethodFromStripeCommandInput>,
	) {
		const { billingAccountId, stripePaymentMethodId } = input;
		super(
			encodePath`/billing-accounts/${billingAccountId}/payment-methods/stripe/${stripePaymentMethodId}`,
		);
	}
}

/**
 * GetPaymentMethodCommand
 *
 */
export class GetPaymentMethodCommand extends Command<
	UndefinedOnPartialDeep<GetPaymentMethodCommandInput>,
	PaymentMethod
> {
	public override method = "get" as const;

	constructor(input: UndefinedOnPartialDeep<GetPaymentMethodCommandInput>) {
		const { billingAccountId, paymentMethodId } = input;
		super(
			encodePath`/billing-accounts/${billingAccountId}/payment-methods/${paymentMethodId}`,
		);
	}
}

/**
 * UpdatePaymentMethodCommand
 *
 */
export class UpdatePaymentMethodCommand extends Command<
	UndefinedOnPartialDeep<UpdatePaymentMethodCommandInput>,
	undefined
> {
	public override method = "put" as const;

	constructor(input: UndefinedOnPartialDeep<UpdatePaymentMethodCommandInput>) {
		const { billingAccountId, paymentMethodId, ...body } = input;
		super(
			encodePath`/billing-accounts/${billingAccountId}/payment-methods/${paymentMethodId}`,
			jsonStringify(body),
		);
	}
}

/**
 * DeletePaymentMethodCommand
 *
 */
export class DeletePaymentMethodCommand extends Command<
	UndefinedOnPartialDeep<DeletePaymentMethodCommandInput>,
	PaymentMethodDeletedLro
> {
	public override method = "delete" as const;

	constructor(input: UndefinedOnPartialDeep<DeletePaymentMethodCommandInput>) {
		const { billingAccountId, paymentMethodId } = input;
		super(
			encodePath`/billing-accounts/${billingAccountId}/payment-methods/${paymentMethodId}`,
		);
	}
}

/**
 * ListBillingSubscriptionsCommand
 *
 */
export class ListBillingSubscriptionsCommand extends Command<
	UndefinedOnPartialDeep<ListBillingSubscriptionsCommandInput>,
	BillingSubscriptions
> {
	public override method = "get" as const;

	constructor(
		input: UndefinedOnPartialDeep<ListBillingSubscriptionsCommandInput>,
	) {
		const { billingAccountId } = input;
		super(encodePath`/billing-accounts/${billingAccountId}/subscriptions`);
	}
}

/**
 * CreateBillingSubscriptionCommand
 *
 */
export class CreateBillingSubscriptionCommand extends Command<
	UndefinedOnPartialDeep<CreateBillingSubscriptionCommandInput>,
	BillingSubscriptionLro
> {
	public override method = "post" as const;

	constructor(
		input: UndefinedOnPartialDeep<CreateBillingSubscriptionCommandInput>,
	) {
		const { billingAccountId, ...body } = input;
		super(
			encodePath`/billing-accounts/${billingAccountId}/subscriptions`,
			jsonStringify(body),
		);
	}
}

/**
 * UpdateBillingSubscriptionCommand
 *
 */
export class UpdateBillingSubscriptionCommand extends Command<
	UndefinedOnPartialDeep<UpdateBillingSubscriptionCommandInput>,
	undefined
> {
	public override method = "put" as const;

	constructor(
		input: UndefinedOnPartialDeep<UpdateBillingSubscriptionCommandInput>,
	) {
		const { billingAccountId, subscriptionId, ...body } = input;
		super(
			encodePath`/billing-accounts/${billingAccountId}/subscriptions/${subscriptionId}`,
			jsonStringify(body),
		);
	}
}

/**
 * CancelSubscriptionCommand
 *
 */
export class CancelSubscriptionCommand extends Command<
	UndefinedOnPartialDeep<CancelSubscriptionCommandInput>,
	undefined
> {
	public override method = "delete" as const;

	constructor(input: UndefinedOnPartialDeep<CancelSubscriptionCommandInput>) {
		const { billingAccountId, subscriptionId } = input;
		super(
			encodePath`/billing-accounts/${billingAccountId}/subscriptions/${subscriptionId}`,
		);
	}
}

/**
 * UpdateBillingSubscriptionPromoCodeCommand
 *
 */
export class UpdateBillingSubscriptionPromoCodeCommand extends Command<
	UndefinedOnPartialDeep<UpdateBillingSubscriptionPromoCodeCommandInput>,
	BillingSubscriptionLro
> {
	public override method = "put" as const;

	constructor(
		input: UndefinedOnPartialDeep<UpdateBillingSubscriptionPromoCodeCommandInput>,
	) {
		const { billingAccountId, subscriptionId, ...body } = input;
		super(
			encodePath`/billing-accounts/${billingAccountId}/subscriptions/${subscriptionId}/promo-code`,
			jsonStringify(body),
		);
	}
}
