/**
 * @generated by @block65/openapi-codegen
 *
 * Do not edit directly
 */

export const nullableStatus = ["active", "paused", "cancelled"] as const;
export const accountTier = ["free", "pro", "enterprise"] as const;
export const billingSubscriptionStatus = ["active", "inactive"] as const;
export const billingSubscriptionInterval = ["monthly", "yearly"] as const;
export const planSku = [
	"donotuse",
	"plasku1",
	"plasku2",
	"plasku3",
	"plasku4",
] as const;
export const paymentMethodBrand = [
	"amex",
	"diners",
	"discover",
	"jcb",
	"mastercard",
	"unionpay",
	"visa",
	"unknown",
] as const;
export const billingLocale = ["en"] as const;
export const billingAccountType = ["standard", "agency", "reseller"] as const;
export const currency = ["usd", "aud", "sgd", "myr", "gbp"] as const;
export const billingAccountStatus = ["nominal", "delinquent"] as const;
export const billingCountry = ["us", "au", "sg", "my", "gb"] as const;
