/**
 * @generated by @block65/openapi-codegen
 *
 * Do not edit directly
 */

// oxlint-disable block65/declaration-comments, block65/no-comment-history, block65/no-narrative-comment, block65/no-trailing-comment-punctuation

import { PublicValidationError } from "@block65/rest-client";
import { sValidator } from "@hono/standard-validator";
import type { ValidationTargets } from "hono";
import {
	cancelSubscriptionCommandParamsSchema,
	createBillingAccountCommandBodySchema,
	createBillingSubscriptionCommandBodySchema,
	createBillingSubscriptionCommandParamsSchema,
	createPaymentMethodCommandParamsSchema,
	deletePaymentMethodCommandParamsSchema,
	getBillingAccountCommandParamsSchema,
	getBillingAccountPortalCommandBodySchema,
	getBillingAccountPortalCommandParamsSchema,
	getOperationCommandParamsSchema,
	getPaymentMethodCommandParamsSchema,
	getPaymentMethodFromStripeCommandParamsSchema,
	importBillingDataCommandParamsSchema,
	linkBillingAccountCommandBodySchema,
	linkBillingAccountCommandParamsSchema,
	listBillingSubscriptionsCommandParamsSchema,
	listPaymentMethodsCommandParamsSchema,
	streamOperationEventsCommandParamsSchema,
	updateBillingAccountCommandBodySchema,
	updateBillingAccountCommandParamsSchema,
	updateBillingSubscriptionCommandBodySchema,
	updateBillingSubscriptionCommandParamsSchema,
	updateBillingSubscriptionPromoCodeCommandBodySchema,
	updateBillingSubscriptionPromoCodeCommandParamsSchema,
	updatePaymentMethodCommandBodySchema,
	updatePaymentMethodCommandParamsSchema,
} from "./valibot.js";

type StandardSchema = Parameters<typeof sValidator>[1];

// The query arrives here as Hono parsed it, and nothing below decodes
// it. A lone value for a repeated-key array stays a string, comma,
// space and pipe joined values stay joined, and a deepObject key stays
// bracketed, so each of those fails validation. A caller sending them
// decodes the query before this middleware or replaces it, reading the
// style and explode from the query spec each operation exports below.
function validate<
	TSchema extends StandardSchema,
	TTarget extends keyof ValidationTargets,
>(target: TTarget, schema: TSchema) {
	return sValidator(target, schema, (result) => {
		if (!result.success) {
			throw PublicValidationError.fromIssues(result.error);
		}
	});
}

export const importBillingData = [
	validate("param", importBillingDataCommandParamsSchema),
] as const;
export const getOperation = [
	validate("param", getOperationCommandParamsSchema),
] as const;
export const streamOperationEvents = [
	validate("param", streamOperationEventsCommandParamsSchema),
] as const;
export const listBillingAccounts = [] as const;
export const createBillingAccount = [
	validate("json", createBillingAccountCommandBodySchema),
] as const;
export const getBillingAccount = [
	validate("param", getBillingAccountCommandParamsSchema),
] as const;
export const updateBillingAccount = [
	validate("json", updateBillingAccountCommandBodySchema),
	validate("param", updateBillingAccountCommandParamsSchema),
] as const;
export const getBillingAccountPortal = [
	validate("json", getBillingAccountPortalCommandBodySchema),
	validate("param", getBillingAccountPortalCommandParamsSchema),
] as const;
export const linkBillingAccount = [
	validate("json", linkBillingAccountCommandBodySchema),
	validate("param", linkBillingAccountCommandParamsSchema),
] as const;
export const listPaymentMethods = [
	validate("param", listPaymentMethodsCommandParamsSchema),
] as const;
export const createPaymentMethod = [
	validate("param", createPaymentMethodCommandParamsSchema),
] as const;
export const getPaymentMethodFromStripe = [
	validate("param", getPaymentMethodFromStripeCommandParamsSchema),
] as const;
export const getPaymentMethod = [
	validate("param", getPaymentMethodCommandParamsSchema),
] as const;
export const updatePaymentMethod = [
	validate("json", updatePaymentMethodCommandBodySchema),
	validate("param", updatePaymentMethodCommandParamsSchema),
] as const;
export const deletePaymentMethod = [
	validate("param", deletePaymentMethodCommandParamsSchema),
] as const;
export const listBillingSubscriptions = [
	validate("param", listBillingSubscriptionsCommandParamsSchema),
] as const;
export const createBillingSubscription = [
	validate("json", createBillingSubscriptionCommandBodySchema),
	validate("param", createBillingSubscriptionCommandParamsSchema),
] as const;
export const updateBillingSubscription = [
	validate("json", updateBillingSubscriptionCommandBodySchema),
	validate("param", updateBillingSubscriptionCommandParamsSchema),
] as const;
export const cancelSubscription = [
	validate("param", cancelSubscriptionCommandParamsSchema),
] as const;
export const updateBillingSubscriptionPromoCode = [
	validate("json", updateBillingSubscriptionPromoCodeCommandBodySchema),
	validate("param", updateBillingSubscriptionPromoCodeCommandParamsSchema),
] as const;
