/**
 * @generated by @block65/openapi-codegen
 *
 * Do not edit directly
 */

import {
	RestServiceClient,
	type ParsedStreamEvent,
	type RestServiceClientConfig,
} from "@block65/rest-client";
import type { UndefinedOnPartialDeep } from "type-fest";
import type {
	BillingAccount,
	BillingAccountList,
	BillingAccountPortal,
	BillingSubscriptionLro,
	BillingSubscriptions,
	CancelSubscriptionCommandInput,
	CreateBillingAccountCommandInput,
	CreateBillingSubscriptionCommandInput,
	CreatePaymentMethodCommandInput,
	DeletePaymentMethodCommandInput,
	GetBillingAccountCommandInput,
	GetBillingAccountPortalCommandInput,
	GetOperationCommandInput,
	GetPaymentMethodCommandInput,
	GetPaymentMethodFromStripeCommandInput,
	ImportBillingDataCommandBodyNonJson,
	ImportBillingDataCommandParams,
	LinkBillingAccountCommandInput,
	ListBillingSubscriptionsCommandInput,
	ListPaymentMethodsCommandInput,
	LongRunningOperation,
	PaymentMethod,
	PaymentMethodDeletedLro,
	PaymentMethodIntendedLro,
	PaymentMethods,
	StreamOperationEventsCommandInput,
	StreamOperationEventsCommandOutput,
	UpdateBillingAccountCommandInput,
	UpdateBillingSubscriptionCommandInput,
	UpdateBillingSubscriptionPromoCodeCommandInput,
	UpdatePaymentMethodCommandInput,
} from "./types.js";

export { ResponseValidationError } from "@block65/rest-client";

type AllInputs =
	| (ImportBillingDataCommandBodyNonJson &
			UndefinedOnPartialDeep<ImportBillingDataCommandParams>)
	| UndefinedOnPartialDeep<CancelSubscriptionCommandInput>
	| UndefinedOnPartialDeep<CreateBillingAccountCommandInput>
	| UndefinedOnPartialDeep<CreateBillingSubscriptionCommandInput>
	| UndefinedOnPartialDeep<CreatePaymentMethodCommandInput>
	| UndefinedOnPartialDeep<DeletePaymentMethodCommandInput>
	| UndefinedOnPartialDeep<GetBillingAccountCommandInput>
	| UndefinedOnPartialDeep<GetBillingAccountPortalCommandInput>
	| UndefinedOnPartialDeep<GetOperationCommandInput>
	| UndefinedOnPartialDeep<GetPaymentMethodCommandInput>
	| UndefinedOnPartialDeep<GetPaymentMethodFromStripeCommandInput>
	| UndefinedOnPartialDeep<LinkBillingAccountCommandInput>
	| UndefinedOnPartialDeep<ListBillingSubscriptionsCommandInput>
	| UndefinedOnPartialDeep<ListPaymentMethodsCommandInput>
	| UndefinedOnPartialDeep<StreamOperationEventsCommandInput>
	| UndefinedOnPartialDeep<UpdateBillingAccountCommandInput>
	| UndefinedOnPartialDeep<UpdateBillingSubscriptionCommandInput>
	| UndefinedOnPartialDeep<UpdateBillingSubscriptionPromoCodeCommandInput>
	| UndefinedOnPartialDeep<UpdatePaymentMethodCommandInput>;
type AllOutputs =
	| BillingAccount
	| BillingAccountList
	| BillingAccountPortal
	| BillingSubscriptionLro
	| BillingSubscriptions
	| LongRunningOperation
	| ParsedStreamEvent<StreamOperationEventsCommandOutput>
	| PaymentMethod
	| PaymentMethodDeletedLro
	| PaymentMethodIntendedLro
	| PaymentMethods
	| undefined;

export class BillingServiceRestApiRestClient extends RestServiceClient<
	AllInputs,
	AllOutputs
> {
	constructor(
		baseUrl: string | URL = new URL("https://api.example.com/"),
		config?: RestServiceClientConfig,
	) {
		super(baseUrl, config);
	}
}
