/**
 * @generated by @block65/openapi-codegen
 *
 * Do not edit directly
 */

// oxlint-disable block65/no-narrative-comment

import type { JsonValue, UndefinedOnPartialDeep } from "type-fest";

export type PromoCode = string;
/** The API version */
export type ApiVersion = "2024-01-01";
export type MaxRetries = 3;
export type DefaultEnabled = true;
/** Optional notes field */
export type NullableNotes = string | null;
export type NullableDiscount = number | null;
export type NullableStatus = "active" | "paused" | "cancelled" | null;
export type AccountTier = "free" | "pro" | "enterprise";
export type EmbedUrl = `https://embed.example.com/${string}`;
export type EventSource =
	| "native"
	| `https://embed.example.com/${string}`
	| `https://syndicated.example.com/${string}`;
export type StripeId = string;
export type DateTime =
	`${number}-${number}-${number}T${number}:${number}:${number}${string}`;
export type BillingSubscriptionStatus = "active" | "inactive";
export type BillingSubscriptionInterval = "monthly" | "yearly";
export type PlanSku =
	| "donotuse"
	| "plasku1"
	| "plasku2"
	| "plasku3"
	| "plasku4";
export type Id = string;
export type BillingSubscriptionIdentifiers = {
	billingAccountId: Id;
	subscriptionId: Id;
};
export type BillingSubscription = BillingSubscriptionIdentifiers & {
	accountId?: Id;
	planSku: PlanSku;
	interval: BillingSubscriptionInterval;
	status: BillingSubscriptionStatus;
	cycleTime: DateTime;
	trialEndTime?: DateTime;
	createdTime: DateTime;
	updatedTime?: DateTime;
};
export type BillingSubscriptions = BillingSubscription[];
export type Uuid = string;
export type LongRunningOperationFail = {
	operationId: Uuid;
	done: boolean;
	result: {
		error: number;
	};
};
export type StringU8 = string;
export type BillingSubscriptionPromoCodeLongRunningOperationSuccess = {
	operationId: Uuid;
	done: boolean;
	result: {
		response: {
			promoCode: StringU8;
		};
	};
};
export type LongRunningOperationIndeterminate = {
	operationId: Uuid;
	done: boolean;
};
export type BillingSubscriptionLro =
	| LongRunningOperationIndeterminate
	| BillingSubscriptionPromoCodeLongRunningOperationSuccess
	| LongRunningOperationFail;
export type UpdateBillingSubscriptionPromoCodeRequest = {
	promoCode: StringU8 | null;
};
/** Reasonable string to be used as a name of a person, or an object */
export type Name = string;
export type UpdateBillingSubscriptionRequest = {
	/** Reasonable string to be used as a name of a person, or an object */
	label?: Name;
	trialEndTime?: DateTime;
};
export type CreateBillingSubscriptionRequest = {
	accountId: Id;
	planSku: PlanSku;
	interval: BillingSubscriptionInterval;
	promoCode?: StringU8;
};
export type PaymentMethodBrand =
	| "amex"
	| "diners"
	| "discover"
	| "jcb"
	| "mastercard"
	| "unionpay"
	| "visa"
	| "unknown";
export type PaymentMethodIdentifiers = {
	billingAccountId: Id;
	paymentMethodId: Id;
};
export type PaymentMethod = PaymentMethodIdentifiers & {
	/** Reasonable string to be used as a name of a person, or an object */
	label: Name;
	expireTime: DateTime;
	humanId: StringU8;
	brand?: PaymentMethodBrand;
};
export type PaymentMethods = PaymentMethod[];
export type PaymentMethodDeletedLongRunningOperationSuccess = {
	operationId: Uuid;
	done: boolean;
	result: {
		response: {
			ok: boolean;
		};
	};
};
export type PaymentMethodDeletedLro =
	| LongRunningOperationIndeterminate
	| PaymentMethodDeletedLongRunningOperationSuccess
	| LongRunningOperationFail;
export type PaymentMethodLongRunningOperationSuccess = {
	operationId: Uuid;
	done: boolean;
	result: {
		response: {
			clientSecret: string;
		};
	};
};
export type PaymentMethodIntendedLro =
	| LongRunningOperationIndeterminate
	| PaymentMethodLongRunningOperationSuccess
	| LongRunningOperationFail;
export type UpdatePaymentMethodRequest = {
	/** Reasonable string to be used as a name of a person, or an object */
	label?: Name;
	isDefault?: boolean;
};
export type LinkBillingAccountRequest = {
	accountId: Id;
};
export type Url = string;
export type BillingAccountPortal = {
	url: Url;
};
export type Origin = string;
export type BillingAccountPortalRequest = {
	origin: Origin;
	accountId: Id;
};
export type TimeZone = string;
export type BillingLocale = "en";
export type BillingAccountType = "standard" | "agency" | "reseller";
export type Currency = "usd" | "aud" | "sgd" | "myr" | "gbp";
export type BillingAccountStatus = "nominal" | "delinquent";
export type BillingCountry = "us" | "au" | "sg" | "my" | "gb";
/** Valid email address with fully qualified public top-level domain */
export type Email = string;
export type BillingAccountIdentifiers = {
	billingAccountId: Id;
};
export type BillingAccount = BillingAccountIdentifiers & {
	/** Reasonable string to be used as a name of a person, or an object */
	name: Name;
	/** Valid email address with fully qualified public top-level domain */
	email: Email;
	country: BillingCountry;
	status: BillingAccountStatus;
	currency: Currency;
	type: BillingAccountType;
	createdTime: DateTime;
	updatedTime?: DateTime;
	locale?: BillingLocale;
	purchaseOrder?: StringU8;
	taxId?: StringU8;
	timeZone?: TimeZone;
	defaultPaymentMethodId?: Id;
};
export type BillingAccountList = BillingAccount[];
export type BillingAccountUpdateRequest = {
	/** Reasonable string to be used as a name of a person, or an object */
	name?: Name;
	/** Valid email address with fully qualified public top-level domain */
	email?: Email;
	country?: BillingCountry;
	timeZone?: TimeZone;
	currency?: Currency;
	locale?: BillingLocale | null;
	purchaseOrder?: StringU8 | null;
	taxId?: StringU8 | null;
};
export type BillingAccountCreateRequest = {
	/** Reasonable string to be used as a name of a person, or an object */
	name: Name;
	/** Valid email address with fully qualified public top-level domain */
	email: Email;
	country: BillingCountry;
	timeZone: TimeZone;
	currency: Currency;
	locale?: BillingLocale | null;
	purchaseOrder?: StringU8 | null;
	taxId?: StringU8 | null;
};
export type LongRunningOperationSuccess = {
	operationId: Uuid;
	done: boolean;
	result: {
		response: Record<string, JsonValue>;
	};
};
export type LongRunningOperation =
	| LongRunningOperationIndeterminate
	| LongRunningOperationFail
	| LongRunningOperationSuccess;
export type ImportBillingDataCommandHeader = {
	"content-type": "application/json" | "text/csv" | "application/xml";
	"content-length": `${bigint}`;
	"x-idempotency-key"?: string;
};
type ImportBillingDataCommandBodyApplicationOctetStream = NonNullable<
	RequestInit["body"]
>;
export type ImportBillingDataCommandBodyNonJson = {
	body: ImportBillingDataCommandBodyApplicationOctetStream;
};
export type ImportBillingDataCommandParams = {
	billingAccountId: Id;
};
export type ImportBillingDataCommandInput =
	ImportBillingDataCommandBodyNonJson & ImportBillingDataCommandParams;
export type InputImportBillingDataCommandResponse =
	UndefinedOnPartialDeep<LongRunningOperation>;
export type GetOperationCommandParams = {
	operationId: Uuid;
};
export type GetOperationCommandInput = GetOperationCommandParams;
export type InputGetOperationCommandResponse =
	UndefinedOnPartialDeep<LongRunningOperation>;
export type StreamOperationEventsCommandParams = {
	operationId: Uuid;
};
export type StreamOperationEventsCommandInput =
	StreamOperationEventsCommandParams;
export type StreamOperationEventsCommandOutput =
	| LongRunningOperation
	| {
			sequence: number;
	  };
export type ListBillingAccountsCommandInput = never;
export type InputListBillingAccountsCommandResponse =
	UndefinedOnPartialDeep<BillingAccountList>;
export type CreateBillingAccountCommandBody = BillingAccountCreateRequest;
export type CreateBillingAccountCommandInput = BillingAccountCreateRequest;
export type InputCreateBillingAccountCommandResponse =
	UndefinedOnPartialDeep<BillingAccount>;
export type GetBillingAccountCommandParams = {
	billingAccountId: Id;
};
export type GetBillingAccountCommandInput = GetBillingAccountCommandParams;
export type InputGetBillingAccountCommandResponse =
	UndefinedOnPartialDeep<BillingAccount>;
export type UpdateBillingAccountCommandParams = {
	billingAccountId: Id;
};
export type UpdateBillingAccountCommandBody = BillingAccountUpdateRequest;
export type UpdateBillingAccountCommandInput = BillingAccountUpdateRequest &
	UpdateBillingAccountCommandParams;
export type InputUpdateBillingAccountCommandResponse =
	UndefinedOnPartialDeep<BillingAccount>;
export type GetBillingAccountPortalCommandParams = {
	billingAccountId: Id;
};
export type GetBillingAccountPortalCommandBody = BillingAccountPortalRequest;
export type GetBillingAccountPortalCommandInput = BillingAccountPortalRequest &
	GetBillingAccountPortalCommandParams;
export type InputGetBillingAccountPortalCommandResponse =
	UndefinedOnPartialDeep<BillingAccountPortal>;
export type LinkBillingAccountCommandParams = {
	billingAccountId: Id;
};
export type LinkBillingAccountCommandBody = LinkBillingAccountRequest;
export type LinkBillingAccountCommandInput = LinkBillingAccountRequest &
	LinkBillingAccountCommandParams;
export type ListPaymentMethodsCommandParams = {
	billingAccountId: Id;
};
export type ListPaymentMethodsCommandInput = ListPaymentMethodsCommandParams;
export type InputListPaymentMethodsCommandResponse =
	UndefinedOnPartialDeep<PaymentMethods>;
export type CreatePaymentMethodCommandParams = {
	billingAccountId: Id;
};
export type CreatePaymentMethodCommandInput = CreatePaymentMethodCommandParams;
export type InputCreatePaymentMethodCommandResponse =
	UndefinedOnPartialDeep<PaymentMethodIntendedLro>;
export type GetPaymentMethodFromStripeCommandParams = {
	billingAccountId: Id;
	stripePaymentMethodId: StripeId;
};
export type GetPaymentMethodFromStripeCommandInput =
	GetPaymentMethodFromStripeCommandParams;
export type InputGetPaymentMethodFromStripeCommandResponse =
	UndefinedOnPartialDeep<PaymentMethod>;
export type GetPaymentMethodCommandParams = {
	billingAccountId: Id;
	paymentMethodId: Id;
};
export type GetPaymentMethodCommandInput = GetPaymentMethodCommandParams;
export type InputGetPaymentMethodCommandResponse =
	UndefinedOnPartialDeep<PaymentMethod>;
export type UpdatePaymentMethodCommandParams = {
	billingAccountId: Id;
	paymentMethodId: Id;
};
export type UpdatePaymentMethodCommandBody = UpdatePaymentMethodRequest;
export type UpdatePaymentMethodCommandInput = UpdatePaymentMethodRequest &
	UpdatePaymentMethodCommandParams;
export type DeletePaymentMethodCommandParams = {
	billingAccountId: Id;
	paymentMethodId: Id;
};
export type DeletePaymentMethodCommandInput = DeletePaymentMethodCommandParams;
export type InputDeletePaymentMethodCommandResponse =
	UndefinedOnPartialDeep<PaymentMethodDeletedLro>;
export type ListBillingSubscriptionsCommandParams = {
	billingAccountId: Id;
};
export type ListBillingSubscriptionsCommandInput =
	ListBillingSubscriptionsCommandParams;
export type InputListBillingSubscriptionsCommandResponse =
	UndefinedOnPartialDeep<BillingSubscriptions>;
export type CreateBillingSubscriptionCommandParams = {
	billingAccountId: Id;
};
export type CreateBillingSubscriptionCommandBody =
	CreateBillingSubscriptionRequest;
export type CreateBillingSubscriptionCommandInput =
	CreateBillingSubscriptionRequest & CreateBillingSubscriptionCommandParams;
export type InputCreateBillingSubscriptionCommandResponse =
	UndefinedOnPartialDeep<BillingSubscriptionLro>;
export type UpdateBillingSubscriptionCommandParams = {
	billingAccountId: Id;
	subscriptionId: Id;
};
export type UpdateBillingSubscriptionCommandBody =
	UpdateBillingSubscriptionRequest;
export type UpdateBillingSubscriptionCommandInput =
	UpdateBillingSubscriptionRequest & UpdateBillingSubscriptionCommandParams;
export type CancelSubscriptionCommandParams = {
	billingAccountId: Id;
	subscriptionId: Id;
};
export type CancelSubscriptionCommandInput = CancelSubscriptionCommandParams;
export type UpdateBillingSubscriptionPromoCodeCommandParams = {
	billingAccountId: Id;
	subscriptionId: Id;
};
export type UpdateBillingSubscriptionPromoCodeCommandBody =
	UpdateBillingSubscriptionPromoCodeRequest;
export type UpdateBillingSubscriptionPromoCodeCommandInput =
	UpdateBillingSubscriptionPromoCodeRequest &
		UpdateBillingSubscriptionPromoCodeCommandParams;
export type InputUpdateBillingSubscriptionPromoCodeCommandResponse =
	UndefinedOnPartialDeep<BillingSubscriptionLro>;
