/**
 * @generated by @block65/openapi-codegen
 *
 * Do not edit directly
 */

// oxlint-disable block65/no-narrative-comment, block65/prefer-exact-optional

import type { JsonValue } from "type-fest";
import * as v from "valibot";

const jsonValueSchema: v.GenericSchema<JsonValue> = v.lazy(() =>
	v.union([
		v.string(),
		v.number(),
		v.boolean(),
		v.null(),
		v.record(v.string(), jsonValueSchema),
		v.array(jsonValueSchema),
	]),
);
export const inputPromoCodeSchema = v.pipe(
	v.string(),
	v.minLength(1),
	v.maxLength(256),
	v.regex(new RegExp("/^[A-Z0-9]$/")),
);
export const promoCodeSchema = inputPromoCodeSchema;
/** The API version */
export const inputApiVersionSchema = v.literal("2024-01-01");
export const apiVersionSchema = inputApiVersionSchema;
export const inputMaxRetriesSchema = v.literal(3);
export const maxRetriesSchema = inputMaxRetriesSchema;
export const inputDefaultEnabledSchema = v.literal(true);
export const defaultEnabledSchema = inputDefaultEnabledSchema;
/** Optional notes field */
export const inputNullableNotesSchema = v.nullable(v.string());
export const nullableNotesSchema = inputNullableNotesSchema;
export const inputNullableDiscountSchema = v.nullable(v.number());
export const nullableDiscountSchema = inputNullableDiscountSchema;
export const inputNullableStatusSchema = v.nullable(
	v.picklist(["active", "paused", "cancelled"]),
);
export const nullableStatusSchema = inputNullableStatusSchema;
export const inputAccountTierSchema = v.picklist(["free", "pro", "enterprise"]);
export const accountTierSchema = inputAccountTierSchema;
export const inputEmbedUrlSchema = v.pipe(
	v.string(),
	v.regex(new RegExp(String.raw`^https://embed\.example\.com/.+$`)),
	v.custom<`https://embed.example.com/${string}`>(() => true),
);
export const embedUrlSchema = inputEmbedUrlSchema;
export const inputEventSourceSchema = v.union([
	v.picklist(["native"]),
	v.pipe(
		v.string(),
		v.regex(new RegExp(String.raw`^https://embed\.example\.com/.+$`)),
		v.custom<`https://embed.example.com/${string}`>(() => true),
	),
	v.pipe(
		v.string(),
		v.regex(new RegExp(String.raw`^https://syndicated\.example\.com/.+$`)),
		v.custom<`https://syndicated.example.com/${string}`>(() => true),
	),
]);
export const eventSourceSchema = inputEventSourceSchema;
export const inputStripeIdSchema = v.pipe(
	v.string(),
	v.minLength(11),
	v.maxLength(255),
	v.regex(new RegExp(String.raw`^(pm|cus|sub)_\w{8,}$`)),
);
export const stripeIdSchema = inputStripeIdSchema;
export const inputDateTimeSchema = v.pipe(
	v.string(),
	v.regex(
		/^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])[Tt ]([01]\d|2[0-3]):[0-5]\d:([0-5]\d|60)(\.\d+)?([Zz]|[+-]([01]\d|2[0-3]):[0-5]\d)$/u,
		"date-time",
	),
	v.custom<`${number}-${number}-${number}T${number}:${number}:${number}${string}`>(
		() => true,
	),
);
export const dateTimeSchema = v.pipe(
	v.string(),
	v.trim(),
	v.regex(
		/^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])[Tt ]([01]\d|2[0-3]):[0-5]\d:([0-5]\d|60)(\.\d+)?([Zz]|[+-]([01]\d|2[0-3]):[0-5]\d)$/u,
		"date-time",
	),
	v.custom<`${number}-${number}-${number}T${number}:${number}:${number}${string}`>(
		() => true,
	),
);
export const inputBillingSubscriptionStatusSchema = v.picklist([
	"active",
	"inactive",
]);
export const billingSubscriptionStatusSchema =
	inputBillingSubscriptionStatusSchema;
export const inputBillingSubscriptionIntervalSchema = v.picklist([
	"monthly",
	"yearly",
]);
export const billingSubscriptionIntervalSchema =
	inputBillingSubscriptionIntervalSchema;
export const inputPlanSkuSchema = v.picklist([
	"donotuse",
	"plasku1",
	"plasku2",
	"plasku3",
	"plasku4",
]);
export const planSkuSchema = inputPlanSkuSchema;
export const inputIdSchema = v.pipe(
	v.string(),
	v.minLength(1),
	v.maxLength(16),
	v.regex(new RegExp("^[a-zA-Z0-9]+$")),
);
export const idSchema = inputIdSchema;
export const inputBillingSubscriptionIdentifiersSchema = v.strictObject({
	billingAccountId: inputIdSchema,
	subscriptionId: inputIdSchema,
});
export const billingSubscriptionIdentifiersSchema =
	inputBillingSubscriptionIdentifiersSchema;
export const inputBillingSubscriptionSchema = v.strictObject({
	...inputBillingSubscriptionIdentifiersSchema.entries,
	accountId: v.optional(inputIdSchema),
	planSku: inputPlanSkuSchema,
	interval: inputBillingSubscriptionIntervalSchema,
	status: inputBillingSubscriptionStatusSchema,
	cycleTime: inputDateTimeSchema,
	trialEndTime: v.optional(inputDateTimeSchema),
	createdTime: inputDateTimeSchema,
	updatedTime: v.optional(inputDateTimeSchema),
});
export const billingSubscriptionSchema = v.strictObject({
	...billingSubscriptionIdentifiersSchema.entries,
	accountId: v.exactOptional(idSchema),
	planSku: planSkuSchema,
	interval: billingSubscriptionIntervalSchema,
	status: billingSubscriptionStatusSchema,
	cycleTime: dateTimeSchema,
	trialEndTime: v.exactOptional(dateTimeSchema),
	createdTime: dateTimeSchema,
	updatedTime: v.exactOptional(dateTimeSchema),
});
export const inputBillingSubscriptionsSchema = v.array(
	inputBillingSubscriptionSchema,
);
export const billingSubscriptionsSchema = inputBillingSubscriptionsSchema;
export const inputUuidSchema = v.pipe(v.string(), v.uuid());
export const uuidSchema = inputUuidSchema;
export const inputLongRunningOperationFailSchema = v.strictObject({
	operationId: inputUuidSchema,
	done: v.literal(true),
	result: v.strictObject({
		error: v.number(),
	}),
});
export const longRunningOperationFailSchema =
	inputLongRunningOperationFailSchema;
export const inputStringU8Schema = v.pipe(
	v.string(),
	v.minLength(1),
	v.maxLength(256),
);
export const stringU8Schema = v.pipe(
	v.string(),
	v.trim(),
	v.minLength(1),
	v.maxLength(256),
);
export const inputBillingSubscriptionPromoCodeLongRunningOperationSuccessSchema =
	v.strictObject({
		operationId: inputUuidSchema,
		done: v.literal(true),
		result: v.strictObject({
			response: v.strictObject({
				promoCode: inputStringU8Schema,
			}),
		}),
	});
export const billingSubscriptionPromoCodeLongRunningOperationSuccessSchema =
	inputBillingSubscriptionPromoCodeLongRunningOperationSuccessSchema;
export const inputLongRunningOperationIndeterminateSchema = v.strictObject({
	operationId: inputUuidSchema,
	done: v.boolean(),
});
export const longRunningOperationIndeterminateSchema =
	inputLongRunningOperationIndeterminateSchema;
export const inputBillingSubscriptionLroSchema = v.union([
	inputLongRunningOperationIndeterminateSchema,
	inputBillingSubscriptionPromoCodeLongRunningOperationSuccessSchema,
	inputLongRunningOperationFailSchema,
]);
export const billingSubscriptionLroSchema = inputBillingSubscriptionLroSchema;
export const inputUpdateBillingSubscriptionPromoCodeRequestSchema = v.pipe(
	v.strictObject({
		promoCode: v.union([inputStringU8Schema, v.null()]),
	}),
	v.minEntries(1),
);
export const updateBillingSubscriptionPromoCodeRequestSchema =
	inputUpdateBillingSubscriptionPromoCodeRequestSchema;
/** Reasonable string to be used as a name of a person, or an object */
export const inputNameSchema = v.pipe(
	v.string(),
	v.minLength(2),
	v.maxLength(512),
);
export const nameSchema = v.pipe(
	v.string(),
	v.trim(),
	v.minLength(2),
	v.maxLength(512),
);
export const inputUpdateBillingSubscriptionRequestSchema = v.pipe(
	v.strictObject({
		label: v.optional(inputNameSchema),
		trialEndTime: v.optional(inputDateTimeSchema),
	}),
	v.minEntries(1),
);
export const updateBillingSubscriptionRequestSchema = v.pipe(
	v.strictObject({
		label: v.exactOptional(nameSchema),
		trialEndTime: v.exactOptional(dateTimeSchema),
	}),
	v.minEntries(1),
);
export const inputCreateBillingSubscriptionRequestSchema = v.strictObject({
	accountId: inputIdSchema,
	planSku: inputPlanSkuSchema,
	interval: inputBillingSubscriptionIntervalSchema,
	promoCode: v.optional(inputStringU8Schema),
});
export const createBillingSubscriptionRequestSchema = v.strictObject({
	accountId: idSchema,
	planSku: planSkuSchema,
	interval: billingSubscriptionIntervalSchema,
	promoCode: v.exactOptional(stringU8Schema),
});
export const inputPaymentMethodBrandSchema = v.picklist([
	"amex",
	"diners",
	"discover",
	"jcb",
	"mastercard",
	"unionpay",
	"visa",
	"unknown",
]);
export const paymentMethodBrandSchema = inputPaymentMethodBrandSchema;
export const inputPaymentMethodIdentifiersSchema = v.strictObject({
	billingAccountId: inputIdSchema,
	paymentMethodId: inputIdSchema,
});
export const paymentMethodIdentifiersSchema =
	inputPaymentMethodIdentifiersSchema;
export const inputPaymentMethodSchema = v.strictObject({
	...inputPaymentMethodIdentifiersSchema.entries,
	label: inputNameSchema,
	expireTime: inputDateTimeSchema,
	humanId: inputStringU8Schema,
	brand: v.optional(inputPaymentMethodBrandSchema),
});
export const paymentMethodSchema = v.strictObject({
	...paymentMethodIdentifiersSchema.entries,
	label: nameSchema,
	expireTime: dateTimeSchema,
	humanId: stringU8Schema,
	brand: v.exactOptional(paymentMethodBrandSchema),
});
export const inputPaymentMethodsSchema = v.array(inputPaymentMethodSchema);
export const paymentMethodsSchema = inputPaymentMethodsSchema;
export const inputPaymentMethodDeletedLongRunningOperationSuccessSchema =
	v.strictObject({
		operationId: inputUuidSchema,
		done: v.literal(true),
		result: v.strictObject({
			response: v.strictObject({
				ok: v.boolean(),
			}),
		}),
	});
export const paymentMethodDeletedLongRunningOperationSuccessSchema =
	inputPaymentMethodDeletedLongRunningOperationSuccessSchema;
export const inputPaymentMethodDeletedLroSchema = v.union([
	inputLongRunningOperationIndeterminateSchema,
	inputPaymentMethodDeletedLongRunningOperationSuccessSchema,
	inputLongRunningOperationFailSchema,
]);
export const paymentMethodDeletedLroSchema = inputPaymentMethodDeletedLroSchema;
export const inputPaymentMethodLongRunningOperationSuccessSchema =
	v.strictObject({
		operationId: inputUuidSchema,
		done: v.literal(true),
		result: v.strictObject({
			response: v.strictObject({
				clientSecret: v.string(),
			}),
		}),
	});
export const paymentMethodLongRunningOperationSuccessSchema = v.strictObject({
	operationId: uuidSchema,
	done: v.literal(true),
	result: v.strictObject({
		response: v.strictObject({
			clientSecret: v.pipe(v.string(), v.trim()),
		}),
	}),
});
export const inputPaymentMethodIntendedLroSchema = v.union([
	inputLongRunningOperationIndeterminateSchema,
	inputPaymentMethodLongRunningOperationSuccessSchema,
	inputLongRunningOperationFailSchema,
]);
export const paymentMethodIntendedLroSchema =
	inputPaymentMethodIntendedLroSchema;
export const inputUpdatePaymentMethodRequestSchema = v.pipe(
	v.strictObject({
		label: v.optional(inputNameSchema),
		isDefault: v.optional(v.boolean()),
	}),
	v.minEntries(1),
);
export const updatePaymentMethodRequestSchema = v.pipe(
	v.strictObject({
		label: v.exactOptional(nameSchema),
		isDefault: v.exactOptional(v.boolean()),
	}),
	v.minEntries(1),
);
export const inputLinkBillingAccountRequestSchema = v.strictObject({
	accountId: inputIdSchema,
});
export const linkBillingAccountRequestSchema =
	inputLinkBillingAccountRequestSchema;
export const inputUrlSchema = v.pipe(
	v.string(),
	v.minLength(1),
	v.maxLength(2048),
	v.regex(new RegExp("^https://.*")),
);
export const urlSchema = inputUrlSchema;
export const inputBillingAccountPortalSchema = v.strictObject({
	url: inputUrlSchema,
});
export const billingAccountPortalSchema = inputBillingAccountPortalSchema;
export const inputOriginSchema = v.pipe(
	v.string(),
	v.minLength(1),
	v.maxLength(263),
	v.regex(new RegExp("^https://.*$")),
);
export const originSchema = inputOriginSchema;
export const inputBillingAccountPortalRequestSchema = v.strictObject({
	origin: inputOriginSchema,
	accountId: inputIdSchema,
});
export const billingAccountPortalRequestSchema =
	inputBillingAccountPortalRequestSchema;
export const inputTimeZoneSchema = v.pipe(
	v.string(),
	v.regex(new RegExp(String.raw`^\w{1,32}/\w{1,32}$`)),
);
export const timeZoneSchema = inputTimeZoneSchema;
export const inputBillingLocaleSchema = v.picklist(["en"]);
export const billingLocaleSchema = inputBillingLocaleSchema;
export const inputBillingAccountTypeSchema = v.picklist([
	"standard",
	"agency",
	"reseller",
]);
export const billingAccountTypeSchema = inputBillingAccountTypeSchema;
export const inputCurrencySchema = v.picklist([
	"usd",
	"aud",
	"sgd",
	"myr",
	"gbp",
]);
export const currencySchema = inputCurrencySchema;
export const inputBillingAccountStatusSchema = v.picklist([
	"nominal",
	"delinquent",
]);
export const billingAccountStatusSchema = inputBillingAccountStatusSchema;
export const inputBillingCountrySchema = v.picklist([
	"us",
	"au",
	"sg",
	"my",
	"gb",
]);
export const billingCountrySchema = inputBillingCountrySchema;
/** Valid email address with fully qualified public top-level domain */
export const inputEmailSchema = v.pipe(
	v.string(),
	v.email(),
	v.minLength(6),
	v.maxLength(512),
);
export const emailSchema = v.pipe(
	v.string(),
	v.trim(),
	v.email(),
	v.minLength(6),
	v.maxLength(512),
);
export const inputBillingAccountIdentifiersSchema = v.strictObject({
	billingAccountId: inputIdSchema,
});
export const billingAccountIdentifiersSchema =
	inputBillingAccountIdentifiersSchema;
export const inputBillingAccountSchema = v.strictObject({
	...inputBillingAccountIdentifiersSchema.entries,
	name: inputNameSchema,
	email: inputEmailSchema,
	country: inputBillingCountrySchema,
	status: inputBillingAccountStatusSchema,
	currency: inputCurrencySchema,
	type: inputBillingAccountTypeSchema,
	createdTime: inputDateTimeSchema,
	updatedTime: v.optional(inputDateTimeSchema),
	locale: v.optional(inputBillingLocaleSchema),
	purchaseOrder: v.optional(inputStringU8Schema),
	taxId: v.optional(inputStringU8Schema),
	timeZone: v.optional(inputTimeZoneSchema),
	defaultPaymentMethodId: v.optional(inputIdSchema),
});
export const billingAccountSchema = v.strictObject({
	...billingAccountIdentifiersSchema.entries,
	name: nameSchema,
	email: emailSchema,
	country: billingCountrySchema,
	status: billingAccountStatusSchema,
	currency: currencySchema,
	type: billingAccountTypeSchema,
	createdTime: dateTimeSchema,
	updatedTime: v.exactOptional(dateTimeSchema),
	locale: v.exactOptional(billingLocaleSchema),
	purchaseOrder: v.exactOptional(stringU8Schema),
	taxId: v.exactOptional(stringU8Schema),
	timeZone: v.exactOptional(timeZoneSchema),
	defaultPaymentMethodId: v.exactOptional(idSchema),
});
export const inputBillingAccountListSchema = v.array(inputBillingAccountSchema);
export const billingAccountListSchema = inputBillingAccountListSchema;
export const inputBillingAccountUpdateRequestSchema = v.pipe(
	v.strictObject({
		name: v.optional(inputNameSchema),
		email: v.optional(inputEmailSchema),
		country: v.optional(inputBillingCountrySchema),
		timeZone: v.optional(inputTimeZoneSchema),
		currency: v.optional(inputCurrencySchema),
		locale: v.optional(v.union([inputBillingLocaleSchema, v.null()])),
		purchaseOrder: v.optional(v.union([inputStringU8Schema, v.null()])),
		taxId: v.optional(v.union([inputStringU8Schema, v.null()])),
	}),
	v.minEntries(1),
);
export const billingAccountUpdateRequestSchema = v.pipe(
	v.strictObject({
		name: v.exactOptional(nameSchema),
		email: v.exactOptional(emailSchema),
		country: v.exactOptional(billingCountrySchema),
		timeZone: v.exactOptional(timeZoneSchema),
		currency: v.exactOptional(currencySchema),
		locale: v.exactOptional(v.union([billingLocaleSchema, v.null()])),
		purchaseOrder: v.exactOptional(v.union([stringU8Schema, v.null()])),
		taxId: v.exactOptional(v.union([stringU8Schema, v.null()])),
	}),
	v.minEntries(1),
);
export const inputBillingAccountCreateRequestSchema = v.strictObject({
	name: inputNameSchema,
	email: inputEmailSchema,
	country: inputBillingCountrySchema,
	timeZone: inputTimeZoneSchema,
	currency: inputCurrencySchema,
	locale: v.optional(v.union([inputBillingLocaleSchema, v.null()])),
	purchaseOrder: v.optional(v.union([inputStringU8Schema, v.null()])),
	taxId: v.optional(v.union([inputStringU8Schema, v.null()])),
});
export const billingAccountCreateRequestSchema = v.strictObject({
	name: nameSchema,
	email: emailSchema,
	country: billingCountrySchema,
	timeZone: timeZoneSchema,
	currency: currencySchema,
	locale: v.exactOptional(v.union([billingLocaleSchema, v.null()])),
	purchaseOrder: v.exactOptional(v.union([stringU8Schema, v.null()])),
	taxId: v.exactOptional(v.union([stringU8Schema, v.null()])),
});
export const inputLongRunningOperationSuccessSchema = v.strictObject({
	operationId: inputUuidSchema,
	done: v.literal(true),
	result: v.strictObject({
		response: v.record(v.string(), jsonValueSchema),
	}),
});
export const longRunningOperationSuccessSchema =
	inputLongRunningOperationSuccessSchema;
export const inputLongRunningOperationSchema = v.union([
	inputLongRunningOperationIndeterminateSchema,
	inputLongRunningOperationFailSchema,
	inputLongRunningOperationSuccessSchema,
]);
export const longRunningOperationSchema = inputLongRunningOperationSchema;
export const inputImportBillingDataCommandResponseSchema =
	inputLongRunningOperationSchema;
export const importBillingDataCommandResponseSchema =
	longRunningOperationSchema;
export const inputImportBillingDataCommandParamsSchema = v.strictObject({
	billingAccountId: inputIdSchema,
});
export const importBillingDataCommandParamsSchema = v.strictObject({
	billingAccountId: idSchema,
});
// oxlint-disable block65/prefer-strict-object -- a request carries headers the document does not name; stripping them is the point
export const inputImportBillingDataCommandHeaderSchema = v.object({
	"content-type": v.picklist([
		"application/json",
		"text/csv",
		"application/xml",
	]),
	"content-length": v.bigint(),
	"x-idempotency-key": v.optional(v.pipe(v.string(), v.uuid())),
});
// oxlint-enable block65/prefer-strict-object
// oxlint-disable block65/prefer-strict-object -- a request carries headers the document does not name; stripping them is the point
export const importBillingDataCommandHeaderSchema = v.object({
	"content-type": v.picklist([
		"application/json",
		"text/csv",
		"application/xml",
	]),
	"content-length": v.union([
		v.pipe(v.string(), v.decimal(), v.toBigint(), v.bigint()),
		v.pipe(v.number(), v.integer(), v.toBigint(), v.bigint()),
		v.bigint(),
	]),
	"x-idempotency-key": v.exactOptional(v.pipe(v.string(), v.uuid())),
});
// oxlint-enable block65/prefer-strict-object
export const inputGetOperationCommandResponseSchema =
	inputLongRunningOperationSchema;
export const getOperationCommandResponseSchema = longRunningOperationSchema;
export const inputGetOperationCommandParamsSchema = v.strictObject({
	operationId: inputUuidSchema,
});
export const getOperationCommandParamsSchema = v.strictObject({
	operationId: uuidSchema,
});
export const inputStreamOperationEventsCommandDataSchema = v.union([
	inputLongRunningOperationSchema,
	v.strictObject({
		sequence: v.pipe(v.number(), v.integer()),
	}),
]);
export const streamOperationEventsCommandDataSchema = v.union([
	longRunningOperationSchema,
	v.strictObject({
		sequence: v.pipe(v.number(), v.integer()),
	}),
]);
export const inputStreamOperationEventsCommandParamsSchema = v.strictObject({
	operationId: inputUuidSchema,
});
export const streamOperationEventsCommandParamsSchema = v.strictObject({
	operationId: uuidSchema,
});
export const inputListBillingAccountsCommandResponseSchema =
	inputBillingAccountListSchema;
export const listBillingAccountsCommandResponseSchema =
	billingAccountListSchema;
export const inputCreateBillingAccountCommandBodySchema =
	inputBillingAccountCreateRequestSchema;
export const createBillingAccountCommandBodySchema =
	billingAccountCreateRequestSchema;
export const inputCreateBillingAccountCommandResponseSchema =
	inputBillingAccountSchema;
export const createBillingAccountCommandResponseSchema = billingAccountSchema;
export const inputGetBillingAccountCommandResponseSchema =
	inputBillingAccountSchema;
export const getBillingAccountCommandResponseSchema = billingAccountSchema;
export const inputGetBillingAccountCommandParamsSchema = v.strictObject({
	billingAccountId: inputIdSchema,
});
export const getBillingAccountCommandParamsSchema = v.strictObject({
	billingAccountId: idSchema,
});
export const inputUpdateBillingAccountCommandBodySchema =
	inputBillingAccountUpdateRequestSchema;
export const updateBillingAccountCommandBodySchema =
	billingAccountUpdateRequestSchema;
export const inputUpdateBillingAccountCommandResponseSchema =
	inputBillingAccountSchema;
export const updateBillingAccountCommandResponseSchema = billingAccountSchema;
export const inputUpdateBillingAccountCommandParamsSchema = v.strictObject({
	billingAccountId: inputIdSchema,
});
export const updateBillingAccountCommandParamsSchema = v.strictObject({
	billingAccountId: idSchema,
});
export const inputGetBillingAccountPortalCommandBodySchema =
	inputBillingAccountPortalRequestSchema;
export const getBillingAccountPortalCommandBodySchema =
	billingAccountPortalRequestSchema;
export const inputGetBillingAccountPortalCommandResponseSchema =
	inputBillingAccountPortalSchema;
export const getBillingAccountPortalCommandResponseSchema =
	billingAccountPortalSchema;
export const inputGetBillingAccountPortalCommandParamsSchema = v.strictObject({
	billingAccountId: inputIdSchema,
});
export const getBillingAccountPortalCommandParamsSchema = v.strictObject({
	billingAccountId: idSchema,
});
export const inputLinkBillingAccountCommandBodySchema =
	inputLinkBillingAccountRequestSchema;
export const linkBillingAccountCommandBodySchema =
	linkBillingAccountRequestSchema;
export const inputLinkBillingAccountCommandParamsSchema = v.strictObject({
	billingAccountId: inputIdSchema,
});
export const linkBillingAccountCommandParamsSchema = v.strictObject({
	billingAccountId: idSchema,
});
export const inputListPaymentMethodsCommandResponseSchema =
	inputPaymentMethodsSchema;
export const listPaymentMethodsCommandResponseSchema = paymentMethodsSchema;
export const inputListPaymentMethodsCommandParamsSchema = v.strictObject({
	billingAccountId: inputIdSchema,
});
export const listPaymentMethodsCommandParamsSchema = v.strictObject({
	billingAccountId: idSchema,
});
export const inputCreatePaymentMethodCommandResponseSchema =
	inputPaymentMethodIntendedLroSchema;
export const createPaymentMethodCommandResponseSchema =
	paymentMethodIntendedLroSchema;
export const inputCreatePaymentMethodCommandParamsSchema = v.strictObject({
	billingAccountId: inputIdSchema,
});
export const createPaymentMethodCommandParamsSchema = v.strictObject({
	billingAccountId: idSchema,
});
export const inputGetPaymentMethodFromStripeCommandResponseSchema =
	inputPaymentMethodSchema;
export const getPaymentMethodFromStripeCommandResponseSchema =
	paymentMethodSchema;
export const inputGetPaymentMethodFromStripeCommandParamsSchema =
	v.strictObject({
		billingAccountId: inputIdSchema,
		stripePaymentMethodId: inputStripeIdSchema,
	});
export const getPaymentMethodFromStripeCommandParamsSchema = v.strictObject({
	billingAccountId: idSchema,
	stripePaymentMethodId: stripeIdSchema,
});
export const inputGetPaymentMethodCommandResponseSchema =
	inputPaymentMethodSchema;
export const getPaymentMethodCommandResponseSchema = paymentMethodSchema;
export const inputGetPaymentMethodCommandParamsSchema = v.strictObject({
	billingAccountId: inputIdSchema,
	paymentMethodId: inputIdSchema,
});
export const getPaymentMethodCommandParamsSchema = v.strictObject({
	billingAccountId: idSchema,
	paymentMethodId: idSchema,
});
export const inputUpdatePaymentMethodCommandBodySchema =
	inputUpdatePaymentMethodRequestSchema;
export const updatePaymentMethodCommandBodySchema =
	updatePaymentMethodRequestSchema;
export const inputUpdatePaymentMethodCommandParamsSchema = v.strictObject({
	billingAccountId: inputIdSchema,
	paymentMethodId: inputIdSchema,
});
export const updatePaymentMethodCommandParamsSchema = v.strictObject({
	billingAccountId: idSchema,
	paymentMethodId: idSchema,
});
export const inputDeletePaymentMethodCommandResponseSchema =
	inputPaymentMethodDeletedLroSchema;
export const deletePaymentMethodCommandResponseSchema =
	paymentMethodDeletedLroSchema;
export const inputDeletePaymentMethodCommandParamsSchema = v.strictObject({
	billingAccountId: inputIdSchema,
	paymentMethodId: inputIdSchema,
});
export const deletePaymentMethodCommandParamsSchema = v.strictObject({
	billingAccountId: idSchema,
	paymentMethodId: idSchema,
});
export const inputListBillingSubscriptionsCommandResponseSchema =
	inputBillingSubscriptionsSchema;
export const listBillingSubscriptionsCommandResponseSchema =
	billingSubscriptionsSchema;
export const inputListBillingSubscriptionsCommandParamsSchema = v.strictObject({
	billingAccountId: inputIdSchema,
});
export const listBillingSubscriptionsCommandParamsSchema = v.strictObject({
	billingAccountId: idSchema,
});
export const inputCreateBillingSubscriptionCommandBodySchema =
	inputCreateBillingSubscriptionRequestSchema;
export const createBillingSubscriptionCommandBodySchema =
	createBillingSubscriptionRequestSchema;
export const inputCreateBillingSubscriptionCommandResponseSchema =
	inputBillingSubscriptionLroSchema;
export const createBillingSubscriptionCommandResponseSchema =
	billingSubscriptionLroSchema;
export const inputCreateBillingSubscriptionCommandParamsSchema = v.strictObject(
	{
		billingAccountId: inputIdSchema,
	},
);
export const createBillingSubscriptionCommandParamsSchema = v.strictObject({
	billingAccountId: idSchema,
});
export const inputUpdateBillingSubscriptionCommandBodySchema =
	inputUpdateBillingSubscriptionRequestSchema;
export const updateBillingSubscriptionCommandBodySchema =
	updateBillingSubscriptionRequestSchema;
export const inputUpdateBillingSubscriptionCommandParamsSchema = v.strictObject(
	{
		billingAccountId: inputIdSchema,
		subscriptionId: inputIdSchema,
	},
);
export const updateBillingSubscriptionCommandParamsSchema = v.strictObject({
	billingAccountId: idSchema,
	subscriptionId: idSchema,
});
export const inputCancelSubscriptionCommandParamsSchema = v.strictObject({
	billingAccountId: inputIdSchema,
	subscriptionId: inputIdSchema,
});
export const cancelSubscriptionCommandParamsSchema = v.strictObject({
	billingAccountId: idSchema,
	subscriptionId: idSchema,
});
export const inputUpdateBillingSubscriptionPromoCodeCommandBodySchema =
	inputUpdateBillingSubscriptionPromoCodeRequestSchema;
export const updateBillingSubscriptionPromoCodeCommandBodySchema =
	updateBillingSubscriptionPromoCodeRequestSchema;
export const inputUpdateBillingSubscriptionPromoCodeCommandResponseSchema =
	inputBillingSubscriptionLroSchema;
export const updateBillingSubscriptionPromoCodeCommandResponseSchema =
	billingSubscriptionLroSchema;
export const inputUpdateBillingSubscriptionPromoCodeCommandParamsSchema =
	v.strictObject({
		billingAccountId: inputIdSchema,
		subscriptionId: inputIdSchema,
	});
export const updateBillingSubscriptionPromoCodeCommandParamsSchema =
	v.strictObject({
		billingAccountId: idSchema,
		subscriptionId: idSchema,
	});
