name: Unit Tests (PR)

on:
  pull_request:
    branches: ['canary', 'master']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'
          node-version-file: .node-version

      - run: make test
